# Generated by Django 4.1.5 on 2023-01-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=30)),
                ("phone", models.PositiveIntegerField()),
                ("is_business", models.PositiveIntegerField(default=False)),
                ("gender", models.CharField(max_length=10)),
                ("profileIntroduce", models.TextField(max_length=20)),
            ],
        ),
    ]
