# Generated by Django 4.1.5 on 2023-01-05 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(max_length=120)),
                ("like", models.PositiveIntegerField()),
                ("reply", models.CharField(max_length=30)),
                (
                    "feed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feeds.feed",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
