# Generated by Django 4.1.5 on 2023-01-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                ("like", models.PositiveIntegerField()),
                ("img", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
