# Generated by Django 4.1.5 on 2023-01-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_business"),
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
    ]
