# Generated by Django 4.1.5 on 2023-01-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_is_business"),
        ("feeds", "0002_feed_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="feed",
            name="like",
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="feed",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
    ]
